name = "aITaskDispatcher"
uuid = "73c77573-14d6-4ed1-bfac-a54f890238a0"
authors = ["John Ferrier"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
DataFrames = "0.21"
======
SafeTestsets = "0.0.1"
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
